# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'FWSideMenu_OC' do
    
    pod 'FWSideMenu'
    # 侧滑关闭页面：https://github.com/forkingdog/FDFullscreenPopGesture
    pod 'FDFullscreenPopGesture'
    
end
